### ISSUE TITLE
`libmamba` cannot resolve conda file

### ISSUE THREAD

**Issue by gcoyle83** [TorchSpatiotemporal/tsl#37]
Attempted to install following directions on the [quickstart](https://torch-spatiotemporal.readthedocs.io/en/latest/usage/quickstart.html#installing-using-conda) page. `libmamba` reported it was unable to resolve the environment due to `pytorch-cuda>=11.7`. Relaxed restriction to `pytorch-cuda>=11.6 ` and was able to install the environment and execute the `gentle introduction` notebook (I did have to `pip install tensorboard` as well).

I'm not sure if this is particular to my machine (Windows 10, Version 22H2), processor (NVIDIA RTX A2000) and driver (537.58) or not, but the modified env spec is: 

```yaml
name: tsl
channels:
  - pytorch
  - pyg
  - nvidia                    # remove for cpu installation
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda>=11.6        # remove for cpu installation
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - lightning
  - pip
  - pip:
      - einops
      - hydra-core
      - numpy>1.20.3
      - omegaconf
      - pandas>=1.4
      - PyYAML
      - scikit-learn
      - scipy
      - tables
      - tensorboard
      - torchmetrics>=0.7
      - tqdm
```
